# Generated by Django 5.2.18 on 2026-10-07 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_failure', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_name', models.CharField(max_length=300)),
                ('sha256', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=10)),
                ('extraction', models.JSONField(default=dict)),
                ('review_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('extract', '객체 추출'), ('takeoff', '길이 산출')], max_length=10)),
                ('request_key', models.CharField(max_length=64, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', '대기'), ('running', '진행'), ('succeeded', '완료'), ('failed', '실패')], default='queued', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('artifact_dir', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='projects.drawing')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='공사명')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='발주처')),
                ('trade', models.CharField(default='급수 (위생)', max_length=40, verbose_name='공종')),
                ('status', models.CharField(choices=[('review', '검토 중'), ('active', '산출 중'), ('done', '검토 완료')], default='review', max_length=20, verbose_name='진행 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawings', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=40)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='projects.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='projects.drawing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('drawing', 'handle'), name='unique_drawing_handle')],
            },
        ),
    ]
