# Generated by Django 5.2.18 on 2026-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='연습·검증용 자료와 수량을 보관할 때 선택하세요. 실제 업무 프로젝트와 구분하여 표시합니다.', verbose_name='테스트 프로젝트'),
        ),
    ]
